### ISSUE TITLE
[document] an important message is missing from the README.md

### ISSUE THREAD

**Issue by nightire** [gabrielcsapo/broccoli-inspector#21]
I think there should be a line of how to view the integrated UI, such as:

> And then, open the `http://localhost:4200/_broccoli-inspector` in your browser.

**Comment by gabrielcsapo** [comment]
This is a good idea, I have to cut a release to show monitors this morning and I will update the readme as well

**Comment by gabrielcsapo** [comment]
fixed in https://github.com/gabrielcsapo/broccoli-inspector/commit/c9b6f150f9eef5edbe417cb6f8bdeeebbf717032
